language: python
python:
- 2.6
- 2.7
script:
- pip install git+git://github.com/pyblish/pyblish-maya.git --no-dependencies
deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist"
  password:
    secure: e6aTFKGHyKDbaBME8MGuACBcV/65sIpsZ1QVSoLHt/QfxmhjEe+cJjSei1RAh5aNOYcJacgrkEfIwQHzB9Rvigysy9aJfUrwDeaxE8aL8ut87eh9iiCM7daAfBzjI/CuhDF1uqb+wNUDl0EfAV0o8+kRVjiCoj72iBCktdPqiro=
  on:
    tags: true
    all_branches: true
    repo: pyblish/pyblish-maya
