language: python
python:
- 2.6
- 2.7
script:
- pip install git+git://github.com/pyblish/pyblish-maya.git --no-dependencies
deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist"
  password:
    secure: Glkhi1myBStgOFjWjhr3r0NJe1+PlDOu60yShMIsxxeYbm0TIs9TSjh2aMqAfqXQFh+ME3KBP97V+ERgqsbKTJxxvjaVH8PjHZSzLR1z3ttw0wh/4O8zwiaGX8FZYMUkIEId6keuedqNMnIgkC7cXCOzNi83NSUbb9miAPgKb8Q=
  on:
    tags: true
    all_branches: true
    repo: pyblish/pyblish-maya