language: python
python:
- 2.6
- 2.7
script:
- pip install git+git://github.com/pyblish/pyblish-maya.git --no-dependencies
deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist"
  password:
    secure: Fh1WVRRn/xAiYDBycQyRqSPet8KQpNCWYhGVEoO2IOxbjR2G+P1BG1rlzDNNPIaccsQhaVuZiaDw/PZNqukNveWHwD1EpAk6IrOCWuYN+GSCM5DJf3KtO8U6D1k0ihAKcAdC48+5Gx8VtmLyiTEXPvsHQhPDGIWvbgZIVdDqIBk=
  on:
    tags: true
    all_branches: true
